name: 'OpenAPI Lint Action'
description: 'Use OpenAPI Linter in GitHub Actions'
author: 'nwestfall'
inputs:
  file:
    required: true
    description: 'Path to file to lint'
  github_token:
    required: true
    description: 'GitHub Personal Access Token'
  configuration_file:
    required: false
    description: 'Configuration file'
  title:
    required: false
    description: 'Title used in github UI'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'umbrella'
  color: 'blue'